apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: codinggyantech/express-api:latest
        ports:
        - containerPort: 3001