apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: my-app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: codinggyantech/react-frontend:latest
        ports:
        - containerPort: 80